# FTB Ultimine Configuration
# Restrict FTB Ultimine to only work on ore blocks

# Set mode to whitelist to only allow specified blocks
mode = "whitelist"
whitelist_enabled = true

# Prevent Ultimine from working on common non-ore blocks
[prevention]
logs = true
leaves = true  
crops = true
plants = true
dirt = true
stone = true
sand = true
gravel = true

# List of allowed block tags and specific blocks (ores only)
allowed_blocks = [
    # Vanilla ore tags
    "#minecraft:coal_ores",
    "#minecraft:iron_ores",
    "#minecraft:gold_ores", 
    "#minecraft:diamond_ores",
    "#minecraft:emerald_ores",
    "#minecraft:lapis_ores",
    "#minecraft:redstone_ores",
    "#minecraft:copper_ores",
    
    # Forge ore tags (comprehensive)
    "#forge:ores",
    "#forge:ores/coal",
    "#forge:ores/iron", 
    "#forge:ores/gold",
    "#forge:ores/diamond",
    "#forge:ores/emerald",
    "#forge:ores/lapis",
    "#forge:ores/redstone",
    "#forge:ores/copper",
    "#forge:ores/tin",
    "#forge:ores/lead",
    "#forge:ores/nickel", 
    "#forge:ores/silver",
    "#forge:ores/uranium",
    "#forge:ores/aluminum",
    "#forge:ores/zinc",
    "#forge:ores/osmium",
    "#forge:ores/fluorite",
    
    # Mod-specific ore tags
    "#mekanism:ores",
    "#thermal:ores", 
    "#immersiveengineering:ores",
    
    # Specific deepslate variants
    "minecraft:deepslate_coal_ore",
    "minecraft:deepslate_iron_ore",
    "minecraft:deepslate_gold_ore",
    "minecraft:deepslate_diamond_ore", 
    "minecraft:deepslate_emerald_ore",
    "minecraft:deepslate_lapis_ore",
    "minecraft:deepslate_redstone_ore",
    "minecraft:deepslate_copper_ore",
    
    # Nether ores
    "minecraft:nether_gold_ore",
    "minecraft:nether_quartz_ore",
    "minecraft:ancient_debris"
]

# Explicitly blacklist problematic blocks
blacklisted_blocks = [
    # Wood and plant materials  
    "#minecraft:logs",
    "#minecraft:leaves",
    "#minecraft:planks",
    "#minecraft:saplings",
    "#minecraft:flowers",
    
    # Crops and farming
    "#minecraft:crops", 
    "minecraft:wheat",
    "minecraft:carrots",
    "minecraft:potatoes",
    "minecraft:beetroots",
    "minecraft:melon",
    "minecraft:pumpkin",
    "minecraft:sugar_cane",
    "minecraft:bamboo",
    
    # Terrain blocks
    "#forge:dirt",
    "#forge:stone",
    "#forge:sand", 
    "#forge:gravel",
    "#forge:cobblestone",
    "minecraft:grass_block",
    "minecraft:dirt",
    "minecraft:stone",
    "minecraft:cobblestone"
]

# Settings
require_tool = false
requires_player_hunger = true
shape = "tunnel" 
max_blocks = 64