name = "cwagecraft"
author = "cwage"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6db34390f3686e24e39a156e0378a44d22904ab9c7c1bbb9220c16d6c7b38de0"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
