name = "cwagecraft"
author = "cwage"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feec3bdd0b848e64b9aaa5aac4838b2a94021e0ff6a1fa112311f1ec38f055c4"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
