name = "cwagecraft"
author = "cwage"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bbccd9c115145e8c753d6d69bfb60638c5414fd40bea7fab85fe5d9d8b15b45"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
