name = "cwagecraft"
author = "cwage"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2b59377ed50217c2461079e0ec4c352a2bf0a6c6052289cdd2fd205ec2cedc0"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
