name = "cwagecraft"
author = "cwage"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0b98e83484c41c210892b9a628890e1e3f0fa7105adc85b58b7102b4ec8a455"

[versions]
forge = "47.3.22"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
