# Tinkers' Construct Configuration for Enhanced Early Game Experience
# This configuration makes tools more accessible and encourages early adoption

[tools]
    # Reduce durability costs for repairs to encourage tool use
    repairCostMultiplier = 0.75
    
    # Allow more modifier slots for customization
    extraModifierSlots = 1
    
    # Make tools easier to modify and enhance
    easierToolModification = true

[materials]
    # Allow more materials to be used in tool construction
    enableMoreMaterials = true
    
    # Reduce material costs for early game tools
    materialCostReduction = 0.8

[balance]
    # Encourage tool use by improving base stats slightly
    toolDurabilityMultiplier = 1.2
    toolDamageMultiplier = 1.1
    
    # Make tool forging more rewarding
    forgingBonusMultiplier = 1.3

[compatibility]
    # Ensure compatibility with leveling addon
    levelingAddonSupport = true