# FTB Ultimine Configuration  
# This configuration restricts FTB Ultimine to only work on ore blocks
# preventing exploitation for wood chopping, farming, and other activities

[general]
# Enable FTB Ultimine functionality
enabled = true

# Use whitelist mode to only allow specific blocks
mode = "whitelist"

# Don't require specific tools
require_tool = false

# Maximum blocks per ultimine operation  
max_blocks = 64

# Exhaustion cost per block
exhaustion_per_block = 0.005

# Mining shape (tunnel, square, etc)
shape = "tunnel"

# Prevent block updates during mining
prevent_block_updates = false

[whitelist]
# Enable whitelist functionality
enabled = true

# Specific blocks (empty - using tags instead)
blocks = []

# Block tags that are allowed (ore blocks only)
tags = [
    # Vanilla ore tags
    "minecraft:coal_ores",
    "minecraft:iron_ores", 
    "minecraft:gold_ores",
    "minecraft:diamond_ores",
    "minecraft:emerald_ores",
    "minecraft:lapis_ores",
    "minecraft:redstone_ores",
    "minecraft:copper_ores",
    
    # Forge comprehensive ore tags
    "forge:ores",
    "forge:ores/coal",
    "forge:ores/iron",
    "forge:ores/gold", 
    "forge:ores/diamond",
    "forge:ores/emerald",
    "forge:ores/lapis",
    "forge:ores/redstone",
    "forge:ores/copper",
    "forge:ores/tin",
    "forge:ores/lead",
    "forge:ores/nickel", 
    "forge:ores/silver",
    "forge:ores/uranium",
    "forge:ores/aluminum",
    "forge:ores/zinc",
    "forge:ores/osmium",
    "forge:ores/fluorite",
    
    # Modpack-specific ore tags
    "mekanism:ores", 
    "thermal:ores",
    "immersiveengineering:ores"
]

[blacklist]
# Enable blacklist to explicitly block problematic blocks
enabled = true

# Specific problematic blocks
blocks = [
    "minecraft:wheat",
    "minecraft:carrots",
    "minecraft:potatoes", 
    "minecraft:beetroots",
    "minecraft:melon",
    "minecraft:pumpkin"
]

# Block tags to explicitly deny
tags = [
    # Wood and plant materials
    "minecraft:logs",
    "minecraft:leaves", 
    "minecraft:planks",
    "minecraft:saplings", 
    "minecraft:flowers",
    
    # Terrain blocks
    "forge:dirt",
    "forge:stone", 
    "forge:sand",
    "forge:gravel",
    "forge:cobblestone",
    
    # Crops
    "minecraft:crops"
]